# Generated by Django 4.2.3 on 2023-10-23 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language_practice_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_practice_room.languagepracticeroom')),
            ],
        ),
    ]
