# Generated by Django 4.2.3 on 2023-12-08 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('native_word', models.CharField(max_length=255)),
                ('foreign_word', models.CharField(max_length=255)),
                ('vocab_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary_set.vocabularyset')),
            ],
        ),
    ]
