# Generated by Django 4.2.3 on 2023-12-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='foreign_word',
            new_name='foreignWord',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='native_word',
            new_name='nativeWord',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='vocab_set',
            new_name='vocabSet',
        ),
    ]
